
export const courses = [
        {
            title:"RECICLAGEM PARA CONDUTORES INFRATORES",
            slug:"reciclagem-para-condutores",
            codigoCurso:1,
            code:"1",
            amount:347.40,
            image_url:"/RECICLAGEM.png",
        },
        {
            title:"ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE ESCOLARES",
            slug:"atualizacao-para-condutores-de-veiculos-de-transporte-de-escolares",
            codigoCurso:2,
            code:"2",
            amount:220,
            image_url:"/ATUALIZAÇÃO_ESCOLAR.png",
        },
        {
            title:"ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE COLETIVO DE PASSAGEIROS",
            slug:"atualizacao-para-condutores-de-veiculos-de-transporte-coletivo-de-escolares-passageiros",
            codigoCurso:3,
            code:"3",
            amount:220,
            image_url:"/ATUALIZAÇÃO_COLETIVO.png",
        },
        {
            title:"ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE CARGAS DE PRODUTOS PERIGOSOS",
            slug:"atualizacao-para-condutores-de-veiculos-de-transporte-de-cargas-de-produtos-perigosos",
            codigoCurso:4,
            code:"4",
            amount:220,
            image_url:"/ATUALIZAÇÃO_MOPP.png",
        },
        {
            title:"ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE EMERGÊNCIA",
            slug:"atualizacao-para-condutores-de-veiculos-de-transporte-de-emergenia",
            codigoCurso:5,
            code:"5",
            amount:220,
            image_url:"/ATUALIZAÇÃO_TRANSPORTE_DE_EMERGENCIA.png",
        },
        {
            title:"ATUALIZAÇÃO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE CARGAS INDIVISÍVEIS",
            slug:"atualizacao-para-condutores-de-veiculos-de-transporte-de-cargas-indivisiveis",
            codigoCurso:6,
            code:"6",
            amount:220,
            image_url:"/Atualização_Indivisíveis.png",
        },
        {
            title:"CURSO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE CARGA INDIVISÍVEL E OUTRAS",
            slug:"curso-para-condutores-de-veiculo-de-transporte-de-carga-indivisivel-e-outras",
            codigoCurso:7,
            code:"7",
            amount:490,
            image_url:"/INDIVISÍVEIS.png",
        },
        {
            title:"CURSO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE PRODUTOS PERIGOSOS",
            slug:"curso-para-condutores-de-veiculo-de-transporte-de-produtos-perigosos",
            codigoCurso:8,
            code:"8",
            amount:490,
            image_url:"/CARGAS_PERIGOSAS_(MOPP).png",
        },
        {
            title:"CURSO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE COLETIVO",
            slug:"curso-para-condutores-de-veiculo-de-transporte-coletivo",
            codigoCurso:9,
            code:"9",
            amount:490,
            image_url:"/COLETIVO.png",
        },
        {
            title:"CURSO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE ESCOLARES",
            slug:"curso-para-condutores-de-veiculo-de-transporte-de-escolares",
            codigoCurso:10,
            code:"10",
            amount:490,
            image_url:"/ESCOLAR.png",
        },
        {
            title:"CURSO PARA CONDUTORES DE VEÍCULO DE TRANSPORTE DE EMERGÊNCIA",
            slug:"curso-para-condutores-de-veiculo-de-transporte-de-emergencia",
            codigoCurso:11,
            code:"11",
            amount:490,
            image_url:"/EMERGÊNCIA.png",
        },
     
    ]