import Head from 'next/head'
import Image from 'next/image'

import { Header } from '@/components/Header/Header'
import { Courses } from '@/sections/Courses/Courses'
import { About } from '@/sections/About/About'
import { Depositions } from '@/sections/Depositions/Depositions'
import { Contact } from '@/sections/Contact/Contact'
import { Footer } from '@/sections/Footer/Footer'
import { FixedNavDesktop } from '@/components/FixedNavDesktop/FixedNavDesktop'
import { useEffect, useRef } from 'react'
import { useInView } from 'framer-motion'



export default function Home() {

  const coursesRef = useRef<any>(null);
  const isCoursesInView = useInView(coursesRef,{amount:0.3});

  const aboutRef = useRef<any>(null);
  const isAboutInView = useInView(aboutRef,{amount:0.7});



  useEffect(() => {
    console.log("Element is in view: ", isCoursesInView);
  }, [isCoursesInView]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Header
      coursesActive={isCoursesInView}
      aboutActive={isAboutInView}
      depositionsActive={false}
      contactActive={false}
      />

        <Courses ref={coursesRef}/>

        <About ref={aboutRef}/>

        <Depositions/>

        <Contact/>

        <Footer/>
      </main>
    </>
  )
}
