import Head from 'next/head'
import Image from 'next/image'

import { Header } from '@/components/Header/Header'
import { Courses } from '@/sections/Courses/Courses'
import { About } from '@/sections/About/About'
import { Depositions } from '@/sections/Depositions/Depositions'
import { Contact } from '@/sections/Contact/Contact'
import { Footer } from '@/sections/Footer/Footer'
import { FixedNavDesktop } from '@/components/FixedNavDesktop/FixedNavDesktop'
import { useEffect, useRef } from 'react'
import { useInView } from 'framer-motion'



export default function Home() {

  const coursesRef = useRef<any>(null);
  const isCoursesInView = useInView(coursesRef,{amount:0.3});

  const aboutRef = useRef<any>(null);
  const isAboutInView = useInView(aboutRef,{amount:1});

  const depositionsRef = useRef<any>(null);
  const isDepositionsInView = useInView(depositionsRef,{amount:1});

  const contactRef = useRef<any>(null);
  const isContactInView = useInView(contactRef,{amount:0.8});


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Header
      coursesActive={isCoursesInView}
      aboutActive={isAboutInView}
      depositionsActive={isDepositionsInView}
      contactActive={isContactInView}
      />

        <Courses ref={coursesRef}/>

        <About ref={aboutRef}/>

        <Depositions ref={depositionsRef}/>

        <Contact ref={contactRef}/>

        <Footer/>
      </main>
    </>
  )
}
